#ifndef ILO_Resources_Header
#define ILO_Resources_Header

#ifndef FUSION_RUNTIME_ONLY

#define RILO_NAME 101
#define RILO_AUTHOR 102
#define RILO_COPYRIGHT 103
#define RILO_DESCRIPTION 104
#define RILO_WEBSITE 105
#define RILO_HELP 106

#define RILOAM_INSERT_ITEM 201
#define RILOAM_INSERT_ITEM_TIMES 202
#define RILOAM_CHANGE_ITEM 203
#define RILOAM_COPY_ITEMS 204
#define RILOAM_COPY_FROM_LIST 205
#define RILOAM_DELETE_ITEMS 206
#define RILOAM_DELETE_ITEMS_REGEX 207
#define RILOAM_CLEAR 208
#define RILOAM_RESERVE 209
#define RILOAM_SAVE_FILE 210
#define RILOAM_LOAD_FILE 211
#define RILOAM_LOAD_STRING 212
#define RILOAM_SORT 213
#define RILOAM_SORT_CUSTOM_RESULT 214
#define RILOAM_CHANGE_CURRENT_LIST 215
#define RILOAM_DELETE_LIST 216
#define RILOAM_USE_GLOBAL_DATA 217
#define RILOAM_USE_LOCAL_DATA 218
#define RILOAM_COPY_LOCAL_TO_GLOBAL 219
#define RILOAM_COPY_GLOBAL_TO_LOCAL 220
#define RILOAM_DELETE_GLOBAL_DATA 221
#define RILOAM_DELETE_LOCAL_DATA 222

#define RILOCM_ON_ERROR 301
#define RILOCM_ON_SORT_CUSTOM 302
#define RILOCM_HAS_ITEM 303
#define RILOCM_HAS_ITEM_REGEX 304

#define RILOEM_GET_ITEM 401
#define RILOEM_GET_LIST_SIZE 402
#define RILOEM_COUNT_ITEM 403
#define RILOEM_COUNT_ITEM_INDEX 404
#define RILOEM_COUNT_ITEM_REGEX 405
#define RILOEM_COUNT_ITEM_REGEX_INDEX 406
#define RILOEM_SERIALIZE_LIST 407
#define RILOEM_SORT_CUSTOM_A 408
#define RILOEM_SORT_CUSTOM_B 409
#define RILOEM_CAPACITY 410
#define RILOEM_LISTS_CURRENT 411
#define RILOEM_LISTS_COUNT 412
#define RILOEM_LISTS_BY_INDEX 413
#define RILOEM_LISTS_CHANGE_STR 414
#define RILOEM_LISTS_CHANGE_NUM 415
#define RILOEM_ERROR_MESSAGE 416

#define RILOP_ITEM 501
#define RILOP_INDEX_INSERT_WRAP 502
#define RILOP_INSERT_TIMES 503
#define RILOP_INDEX 504
#define RILOP_INDEX_START 505
#define RILOP_INDEX_END_WRAP 506
#define RILOP_INDEX_COPY_BEFORE 507
#define RILOP_COPY_MODE 508
#define RILOP_FILEPATH 509
#define RILOP_DELIMITER 510
#define RILOP_ESCAPE 511
#define RILOP_LISTSTRING 512
#define RILOP_SORT_ORDER 513
#define RILOP_SORT_ORDER_CUSTOM_RESULT 514
#define RILOP_RESERVE_CAPACITY 515
#define RILOP_REGEX 516
#define RILOP_LISTNAME 517
#define RILOP_OCCURRENCE 518
#define RILOP_GLOBAL_DATA_NAME 519

#define RILOA_INSERT 601
#define RILOA_INSERT_TIMES 602
#define RILOA_SET 603
#define RILOA_COPY 604
#define RILOA_ERASE 605
#define RILOA_CLEAR 606
#define RILOA_SAVE_FILE 607
#define RILOA_LOAD_FILE 608
#define RILOA_LOAD_STRING 609
#define RILOA_SORT 610
#define RILOA_SORT_CUSTOM_RESULT 611
#define RILOA_RESERVE_CAPACITY 612
#define RILOA_ERASE_REGEX 613
#define RILOA_CHANGE_CURRENT_LIST 614
#define RILOA_DELETE_LIST 615
#define RILOA_COPY_FROM_LIST 616
#define RILOA_USE_GLOBAL_DATA 617
#define RILOA_USE_LOCAL_DATA 618
#define RILOA_COPY_LOCAL_TO_GLOBAL 619
#define RILOA_COPY_GLOBAL_TO_LOCAL 620
#define RILOA_DELETE_GLOBAL_DATA 621
#define RILOA_DELETE_LOCAL_DATA 622

#define RILOC_CONTAINS 701
#define RILOC_SORT_CUSTOM 702
#define RILOC_ERROR 703
#define RILOC_CONTAINS_REGEX 704

#define RILOE_ITEM 801
#define RILOE_SIZE 802
#define RILOE_COUNT 803
#define RILOE_COUNT_INDEX 804
#define RILOE_SERIALIZE 805
#define RILOE_SORT_CUSTOM_A 806
#define RILOE_SORT_CUSTOM_B 807
#define RILOE_CAPACITY 808
#define RILOE_COUNT_REGEX 809
#define RILOE_COUNT_REGEX_INDEX 810
#define RILOE_LISTS_CURRENT 811
#define RILOE_LISTS_COUNT 812
#define RILOE_LISTS_BY_INDEX 813
#define RILOE_LISTS_CHANGE_STR 814
#define RILOE_LISTS_CHANGE_NUM 815
#define RILOE_ERROR_MESSAGE 816

#define RILOPR_VERSION_NAME 901
#define RILOPR_VERSION_DESC 902
#define RILOPR_NUM_LISTS_NAME 903
#define RILOPR_NUM_LISTS_DESC 904
#define RILOPR_NEW_LIST_NAME 905
#define RILOPR_NEW_LIST_DESC 906
#define RILOPR_NEW_LIST_TEXT 907
#define RILOPR_LIST_FOLDER_DESC 908
#define RILOPR_LIST_NAME_NAME 909
#define RILOPR_LIST_NAME_DESC 910
#define RILOPR_LIST_SIZE_NAME 911
#define RILOPR_LIST_SIZE_DESC 912
#define RILOPR_EDIT_MODE_NAME 913
#define RILOPR_EDIT_MODE_DESC 914
#define RILOPR_EDIT_MODE_BUTTON 915
#define RILOPR_EDIT_MODE_INSERT 916
#define RILOPR_EDIT_MODE_DELETE 917
#define RILOPR_DELIM_NAME 918
#define RILOPR_DELIM_DESC 919
#define RILOPR_ESC_NAME 920
#define RILOPR_ESC_DESC 921
#define RILOPR_LIST_MULTILINE_NAME 922
#define RILOPR_LIST_MULTILINE_DESC 923
#define RILOPR_LIST_ITEM_DESC 924
#define RILOPR_NEW_ITEM_NAME 925
#define RILOPR_NEW_ITEM_DESC 926
#define RILOPR_NEW_ITEM_TEXT 927
#define RILOPR_CONFIRM_DELETE_TITLE 928
#define RILOPR_CONFIRM_DELETE_MESSAGE 929

#endif //FUSION_RUNTIME_ONLY

#endif
